"""Agent 1 - FDD Agent (blueprint section 4).

Analyses all uploaded requirement material and produces a production-ready
Functional Design Document in the client template, plus a flag report listing
every low-confidence item for the designer/architect gate.
"""
from __future__ import annotations

from pathlib import Path
from typing import Any

from core.models import Artifact, DuplicateDecision, Phase
from rendering.docx_writer import render

from .base import BaseAgent, Composition


class FDDAgent(BaseAgent):
    agent_id = "1"
    name = "FDD Agent"
    phase = Phase.FDD
    doc_type = "fdd"
    role = (
        "Produce a complete, production-ready Functional Design Document from the "
        "uploaded requirement material, written so a Maximo designer can hand it "
        "straight to a technical lead."
    )
    inputs_description = (
        "- Raw requirement material (ADO stories, decisions, notes, transcripts)\n"
        "- Prior art retrieved from the AI Brain\n"
        "- The list of Maximo names already validated against the environment"
    )
    output_format = (
        "Markdown document. ALWAYS include:\n"
        "# Functional Design Document\n"
        "## 1. Document Control\n"
        "## 2. Executive Summary\n"
        "## 3. Business Context\n"
        "## 4. Scope  (### 4.1 In Scope / ### 4.2 Out of Scope)\n"
        "## 5. Functional Requirements  (table: Req ID | Requirement | Change Type | Maximo Object | Priority)\n"
        "## 8. Assumptions and Dependencies\n"
        "## 9. Open Questions\n\n"
        "INCLUDE ONLY IF RELEVANT to the change items:\n"
        "## 6. Business Rules — only if conditional logic, validation rules, or obligation rules exist\n"
        "## 7. Process Flow — only if a multi-step workflow or process sequence changes\n\n"
        "Use GitHub-flavoured markdown tables. Never generate a section just to leave it empty or generic."
    )
    skill_files = ("mx_core_SKILL.md", "mx_functional_docs_SKILL.md", "mx_pm_wo_SKILL.md")

    # -- gather ------------------------------------------------------------
    def gather(self) -> dict[str, Any]:
        process = self.ctx.process
        for item in self.change_items():
            self.ctx.validator.check_change_item(item, process, self.report)

        # Every status named in the material is checked too.
        for status_group in ("cu", "workorder"):
            for item in self.change_items():
                for token in _status_tokens(item.description, process, status_group):
                    self.report.add(self.ctx.validator.status(token, process, status_group))

        return {
            "requirements": self.ctx.state.requirements,
            "change_items": self.change_items(),
            "prior_art": self.prior_art(),
            "validation": self.report.summary(),
            "analysis_context": self._get_analysis_context(),
        }

    def _get_analysis_context(self) -> str:
        """Read the approved Requirements Analysis document + gate answers."""
        result = self.ctx.state.result(Phase.ANALYSIS)
        if not result:
            return ""
        parts: list[str] = []
        for artifact in result.artifacts:
            if artifact.name.endswith(".md") and "flag" not in artifact.name.lower():
                p = Path(artifact.path)
                if p.exists():
                    parts.append(p.read_text(encoding="utf-8")[:4000])
                    break
        gate = self.ctx.state.gate(Phase.ANALYSIS)
        if gate.comment:
            parts.append(f"BUSINESS ANSWERS TO OPEN QUESTIONS:\n{gate.comment}")
        return "\n\n".join(parts)

    # -- compose -----------------------------------------------------------
    def compose(self, facts: dict[str, Any], duplicate: DuplicateDecision) -> Composition:
        user_prompt = self._user_prompt(facts, duplicate)
        text, generated_by = self.ask_model(user_prompt, max_tokens=8000)

        if text:
            body, flags = self.parse_flags(text, "FDD")
        else:
            body = self._deterministic(facts, duplicate)
            flags = []
            generated_by = "deterministic"

        flags.extend(self._confidence_flags())
        summary = (
            f"FDD covering {len(facts['change_items'])} change item(s). "
            f"{self.report.summary()} Generated by {generated_by}."
        )
        return Composition(body=body, summary=summary, flags=flags, generated_by=generated_by)

    def _user_prompt(self, facts: dict[str, Any], duplicate: DuplicateDecision) -> str:
        items = "\n".join(
            f"- [{i.change_type.value}] {i.title}\n  {i.description[:400]}"
            for i in facts["change_items"]
        )
        dup_note = ""
        if duplicate.found and duplicate.best:
            dup_note = (
                f"\nPRIOR DOCUMENT DETECTED (similarity {duplicate.similarity:.2f}): "
                f"'{duplicate.best.title}' v{duplicate.best.version}. "
                "The user will decide Update vs New. Keep your section numbering and "
                "terminology consistent with it.\n"
            )
        analysis_block = ""
        if facts.get("analysis_context"):
            analysis_block = (
                f"REQUIREMENTS ANALYSIS (pre-approved — includes business answers to open questions):\n"
                f"{facts['analysis_context']}\n\n"
            )
        return (
            f"RUN: {self.ctx.state.title}\n"
            f"BUSINESS PROCESS: {self.ctx.process_name}\n{dup_note}\n"
            f"{analysis_block}"
            f"PRIOR ART FROM AI BRAIN:\n{facts['prior_art']}\n\n"
            f"VALIDATED MAXIMO FACTS:\n{self.validated_facts_block()}\n\n"
            f"CHANGE ITEMS IDENTIFIED:\n{items}\n\n"
            f"RAW SOURCE MATERIAL:\n{self.ctx.source_material[:60000]}\n\n"
            f"Write the Functional Design Document now. "
            f"Only include sections listed as relevant in the Requirements Analysis above. "
            f"Use the business answers to open questions to populate fields accurately.{self.revision_block()}"
        )

    def _deterministic(self, facts: dict[str, Any], duplicate: DuplicateDecision) -> str:
        """Template-driven FDD used when no model is configured.

        Parses the requirement descriptions to extract Maximo-specific detail and
        uses the narrate() function to inject IBM Maximo-accurate prose into each
        section based on the detected implementation pattern.
        """
        from ._extract import field_spec, business_rules, process_flow_steps, narrate

        state = self.ctx.state
        process = self.ctx.process
        items = facts["change_items"]
        applications = process.get("applications") or [self.ctx.process_name]
        app = applications[0]

        # Get Maximo-specific narrative based on what the requirement describes
        nb = narrate(items, [], process)
        pattern = nb.get("pattern", "config")

        # --- Section 5: requirements table -----------------------------------
        rows = [
            "| Req ID | Requirement | Change Type | Maximo Object | Attribute | Type | Length | Mandatory | Priority |",
            "|---|---|---|---|---|---|---|---|---|",
        ]
        for n, item in enumerate(items, 1):
            spec = field_spec(item.description or "")
            ftype = spec.get("type", "—")
            flen = str(spec.get("length", "—"))
            mand = "Yes" if spec.get("mandatory") else ("No" if "mandatory" in spec else "—")
            priority = "High" if item.confidence >= 0.8 else ("Medium" if item.confidence >= 0.6 else "Low")
            rows.append(
                f"| FR-{n:03d} | {_cell(item.title, 120)} | {item.change_type.value} | "
                f"{item.maximo_object or '—'} | {item.maximo_attribute or '—'} | "
                f"{ftype} | {flen} | {mand} | {priority} |"
            )
            rows.append(
                f"| | *{_cell(item.description, 300)}* | | | | | | | |"
            )

        # --- Section 6: business rules ---------------------------------------
        # Use pattern-specific rules if available, else extract from text
        narrated_rules = nb.get("business_rules") or []
        extracted_rules = narrated_rules if narrated_rules else business_rules(items)
        if not extracted_rules:
            extracted_rules = [
                f"- **BR-{n:03d}** ({item.change_type.value}) — {_cell(item.description, 200)}"
                for n, item in enumerate(items, 1)
            ]

        # --- Section 7: process flow -----------------------------------------
        narrated_flow = nb.get("process_flow") or []
        flow_steps = narrated_flow if narrated_flow else process_flow_steps(items, self.ctx.process_name, applications)

        # --- Open questions --------------------------------------------------
        open_questions = [
            f"- {f.item}: {f.reason}" for f in self.report.to_flags("FDD")
        ] or ["- None outstanding at the time of writing."]

        dup_line = ""
        if duplicate.found and duplicate.best:
            dup_line = (
                f"\n> Prior art: **{duplicate.best.title}** (v{duplicate.best.version}, "
                f"similarity {duplicate.similarity:.2f}) already exists in the AI Brain. "
                "Confirm Update vs New at the review gate.\n"
            )

        in_scope = "\n".join(f"- {_cell(i.title)}" for i in items) or "- See source material."

        # Specific objects detected
        objects_in_scope = sorted({i.maximo_object for i in items if i.maximo_object})
        objects_line = (
            f"Objects in scope: `{'`, `'.join(objects_in_scope)}`" if objects_in_scope
            else "Maximo objects to be confirmed against the environment."
        )

        # Pattern-specific dependencies
        pattern_deps: dict[str, list[str]] = {
            "pm_wo_multiasset": [
                "- `PMWOEGENCRON` cron task must be active and correctly configured in the target site.",
                "- PM records with MULTIASSETLOCCI rows must exist in the test environment to validate the copy.",
                "- MAS Inspections application must be configured if INSPECTIONFORM field propagation is required (MAS 8/9).",
            ],
            "pm_wo_field_copy": [
                "- PM records must exist in the test environment with the source field populated.",
                "- `PMWOEGENCRON` cron task must be active and correctly configured.",
            ],
            "integration": [
                "- External system end point (URL, credentials) must be confirmed before Agent 3B begins.",
                "- Object Structure field mapping must be approved by both the Maximo team and the receiving system team.",
            ],
        }
        extra_deps = "\n".join(pattern_deps.get(pattern, []))

        return f"""# Functional Design Document

## 1. Document Control

| Field | Value |
|---|---|
| Document | Functional Design Document |
| Business process | {process.get('label', self.ctx.process_name)} ({self.ctx.process_name}) |
| Platform | IBM Maximo {self.ctx.cfg.maximo_version} |
| Domain | {self.ctx.cfg.domain} |
| Run ID | {state.run_id} |
| Title | {state.title} |
| Status | Draft — awaiting Designer / Architect review |
| Validation source | {self.ctx.validator.source_label()} |
{dup_line}
## 2. Executive Summary

{nb['executive_summary']}

{self.report.summary()}

All {len(items)} change item(s) listed in section 5 must be approved at the FDD gate
before the Technical Design Document (TDD) is commissioned.

## 3. Business Context

{nb['business_context']}

{process.get('description', '').strip()}

Source material: {', '.join(sorted({r.source for r in state.requirements})) or 'uploaded requirement material'}.

## 4. Scope

### 4.1 In Scope

{in_scope}

{objects_line}

### 4.2 Out of Scope

- Any change to a business process other than **{self.ctx.process_name}**.
- Infrastructure, licensing and Maximo environment provisioning.
- Changes not traceable to a requirement in section 5 of this document.
- Data migration or retrospective population of new fields unless explicitly listed in section 4.1.

## 5. Functional Requirements

{chr(10).join(rows)}

> **Note**: Rows in *italics* contain the full requirement text for traceability.
> `—` in Type / Length / Mandatory means the value must be confirmed with the business owner before the TDD gate.

## 6. Business Rules

{chr(10).join(extracted_rules)}

## 7. Process Flow

{chr(10).join(flow_steps)}

## 8. Assumptions and Dependencies

- IBM Maximo {self.ctx.cfg.maximo_version} is deployed and accessible in the delivery and test environments.
- The {self.ctx.validator.source_label()} has been used for all Maximo object and attribute name validation.
- All Maximo object and attribute names shown as `—` in section 5 must be confirmed against the live environment before the TDD gate.
- Security groups that currently hold access to `{app}` will be updated to cover any new fields; no net-new security groups are anticipated.
- The delivery team holds change-management approval to modify the target Maximo instance.
{extra_deps}

## 9. Open Questions

{chr(10).join(open_questions)}
"""

    def _confidence_flags(self):
        """Flag any change item the classifier was not confident about."""
        threshold = self.ctx.cfg.confidence_threshold
        from core.models import Flag

        out = []
        for item in self.change_items():
            if item.confidence < threshold:
                out.append(
                    Flag(
                        section="5. Functional Requirements",
                        item=item.title[:80],
                        reason=(
                            f"Change type classified as '{item.change_type.value}' with "
                            f"confidence {item.confidence:.2f}, below the {threshold} threshold."
                        ),
                        confidence=item.confidence,
                        severity="warn",
                        suggestion="Confirm the change type at the review gate.",
                    )
                )
        return out

    # -- emit --------------------------------------------------------------
    def emit(self, composition: Composition) -> list[Artifact]:
        out = self.ctx.artifact_dir("01_fdd")
        artifacts: list[Artifact] = []

        md_path = out / "FDD.md"
        md_path.write_text(composition.body, encoding="utf-8")
        artifacts.append(self.register_artifact(md_path, kind="md", description="FDD source markdown"))

        docx_path = out / "FDD.docx"
        render(
            composition.body,
            template=self.ctx.cfg.template_path("fdd"),
            target=docx_path,
            title=f"{self.ctx.process_name} - Functional Design Document",
            subtitle=self.ctx.state.title,
        )
        artifacts.append(
            self.register_artifact(docx_path, kind="docx", description="Production-ready FDD")
        )

        flag_path = out / "FDD_flag_report.md"
        flag_path.write_text(self._flag_report(composition), encoding="utf-8")
        artifacts.append(
            self.register_artifact(flag_path, kind="md", description="Low-confidence items for review")
        )
        return artifacts

    def _flag_report(self, composition: Composition) -> str:
        flags = composition.flags
        lines = [
            "# FDD Flag Report",
            "",
            f"Run: {self.ctx.state.run_id}",
            f"Validation source: {self.ctx.validator.source_label()}",
            "",
            self.report.summary(),
            "",
        ]
        if not flags:
            lines.append("No items fell below the confidence threshold. Nothing requires review.")
            return "\n".join(lines)

        lines += [
            f"{len(flags)} item(s) require human review before this FDD is approved.",
            "",
            "| # | Section | Item | Confidence | Severity | Reason | Suggestion |",
            "|---|---|---|---|---|---|---|",
        ]
        for n, f in enumerate(sorted(flags, key=lambda x: x.confidence), 1):
            lines.append(
                f"| {n} | {_cell(f.section)} | {_cell(f.item)} | {f.confidence:.2f} | "
                f"{f.severity} | {_cell(f.reason)} | {_cell(f.suggestion) or '-'} |"
            )
        return "\n".join(lines)


def _cell(text: str, width: int = 300) -> str:
    """Make text safe for a markdown table cell."""
    clean = " ".join((text or "").split()).replace("|", "\\|")
    return clean[:width] + ("..." if len(clean) > width else "")


def _status_tokens(text: str, process: dict, group: str) -> list[str]:
    """Statuses from `group` that actually appear in the text."""
    allowed = [s for s in (process.get("statuses", {}) or {}).get(group, [])]
    upper = (text or "").upper()
    return [s for s in allowed if f" {s}" in upper or f"{s} " in upper]
