"""Agent 1 - FDD Agent (blueprint section 4).

Analyses all uploaded requirement material and produces a production-ready
Functional Design Document in the client template, plus a flag report listing
every low-confidence item for the designer/architect gate.
"""
from __future__ import annotations

from typing import Any

from core.models import Artifact, DuplicateDecision, Phase
from rendering.docx_writer import render

from .base import BaseAgent, Composition


class FDDAgent(BaseAgent):
    agent_id = "1"
    name = "FDD Agent"
    phase = Phase.FDD
    doc_type = "fdd"
    role = (
        "Produce a complete, production-ready Functional Design Document from the "
        "uploaded requirement material, written so a Maximo designer can hand it "
        "straight to a technical lead."
    )
    inputs_description = (
        "- Raw requirement material (ADO stories, decisions, notes, transcripts)\n"
        "- Prior art retrieved from the AI Brain\n"
        "- The list of Maximo names already validated against the environment"
    )
    output_format = (
        "Markdown following exactly these sections:\n"
        "# Functional Design Document\n"
        "## 1. Document Control\n"
        "## 2. Executive Summary\n"
        "## 3. Business Context\n"
        "## 4. Scope\n"
        "### 4.1 In Scope\n"
        "### 4.2 Out of Scope\n"
        "## 5. Functional Requirements   (a table: Req ID | Requirement | Change Type | Maximo Object | Priority)\n"
        "## 6. Business Rules\n"
        "## 7. Process Flow\n"
        "## 8. Assumptions and Dependencies\n"
        "## 9. Open Questions\n"
        "Use GitHub-flavoured markdown tables. No other sections."
    )
    skill_files = ("mx_core_SKILL.md", "mx_functional_docs_SKILL.md")

    # -- gather ------------------------------------------------------------
    def gather(self) -> dict[str, Any]:
        process = self.ctx.process
        for item in self.change_items():
            self.ctx.validator.check_change_item(item, process, self.report)

        # Every status named in the material is checked too.
        for status_group in ("cu", "workorder"):
            for item in self.change_items():
                for token in _status_tokens(item.description, process, status_group):
                    self.report.add(self.ctx.validator.status(token, process, status_group))

        return {
            "requirements": self.ctx.state.requirements,
            "change_items": self.change_items(),
            "prior_art": self.prior_art(),
            "validation": self.report.summary(),
        }

    # -- compose -----------------------------------------------------------
    def compose(self, facts: dict[str, Any], duplicate: DuplicateDecision) -> Composition:
        user_prompt = self._user_prompt(facts, duplicate)
        text, generated_by = self.ask_model(user_prompt, max_tokens=8000)

        if text:
            body, flags = self.parse_flags(text, "FDD")
        else:
            body = self._deterministic(facts, duplicate)
            flags = []
            generated_by = "deterministic"

        flags.extend(self._confidence_flags())
        summary = (
            f"FDD covering {len(facts['change_items'])} change item(s). "
            f"{self.report.summary()} Generated by {generated_by}."
        )
        return Composition(body=body, summary=summary, flags=flags, generated_by=generated_by)

    def _user_prompt(self, facts: dict[str, Any], duplicate: DuplicateDecision) -> str:
        items = "\n".join(
            f"- [{i.change_type.value}] {i.title}\n  {i.description[:400]}"
            for i in facts["change_items"]
        )
        dup_note = ""
        if duplicate.found and duplicate.best:
            dup_note = (
                f"\nPRIOR DOCUMENT DETECTED (similarity {duplicate.similarity:.2f}): "
                f"'{duplicate.best.title}' v{duplicate.best.version}. "
                "The user will decide Update vs New. Keep your section numbering and "
                "terminology consistent with it.\n"
            )
        return (
            f"RUN: {self.ctx.state.title}\n"
            f"BUSINESS PROCESS: {self.ctx.process_name}\n{dup_note}\n"
            f"PRIOR ART FROM AI BRAIN:\n{facts['prior_art']}\n\n"
            f"VALIDATED MAXIMO FACTS:\n{self.validated_facts_block()}\n\n"
            f"CHANGE ITEMS IDENTIFIED:\n{items}\n\n"
            f"RAW SOURCE MATERIAL:\n{self.ctx.source_material[:30000]}\n\n"
            "Write the Functional Design Document now."
        )

    def _deterministic(self, facts: dict[str, Any], duplicate: DuplicateDecision) -> str:
        """Template-driven FDD used when no model is configured.

        Produces the same section structure so downstream agents and the DOCX
        renderer behave identically with or without a model.
        """
        state = self.ctx.state
        process = self.ctx.process
        items = facts["change_items"]

        rows = [
            "| Req ID | Requirement | Change Type | Maximo Object | Priority |",
            "|---|---|---|---|---|",
        ]
        for n, item in enumerate(items, 1):
            rows.append(
                f"| FR-{n:03d} | {_cell(item.description)} | {item.change_type.value} | "
                f"{item.maximo_object or 'To be confirmed'} | {'High' if item.confidence >= 0.7 else 'Medium'} |"
            )

        business_rules = [
            f"- **BR-{n:03d}** - {_cell(item.description)}"
            for n, item in enumerate(items, 1)
            if item.change_type.value in {"customisation", "workflow"}
        ] or ["- No conditional business rules identified in the source material."]

        open_questions = [
            f"- {f.item}: {f.reason}" for f in self.report.to_flags("FDD")
        ] or ["- None outstanding at the time of writing."]

        dup_line = ""
        if duplicate.found and duplicate.best:
            dup_line = (
                f"\n> Prior art: **{duplicate.best.title}** (v{duplicate.best.version}, "
                f"similarity {duplicate.similarity:.2f}) already exists in the AI Brain. "
                "Confirm Update vs New at the review gate.\n"
            )

        in_scope = "\n".join(f"- {_cell(i.title)}" for i in items) or "- See source material."

        return f"""# Functional Design Document

## 1. Document Control

| Field | Value |
|---|---|
| Document | Functional Design Document |
| Business process | {process.get('label', self.ctx.process_name)} ({self.ctx.process_name}) |
| Platform | IBM Maximo {self.ctx.cfg.maximo_version} |
| Domain | {self.ctx.cfg.domain} |
| Run ID | {state.run_id} |
| Status | Draft - awaiting {process.get('gate_role', 'designer / architect')} review |
| Validation source | {self.ctx.validator.source_label()} |
{dup_line}
## 2. Executive Summary

This document specifies the functional design for {len(items)} change item(s) in the
{process.get('label', self.ctx.process_name)} process. {self.report.summary()}

## 3. Business Context

{process.get('description', 'Business context to be confirmed with the process owner.').strip()}

The changes described here originate from: {', '.join(sorted({r.source for r in state.requirements})) or 'uploaded requirement material'}.

## 4. Scope

### 4.1 In Scope

{in_scope}

### 4.2 Out of Scope

- Any change to a business process other than {self.ctx.process_name}.
- Infrastructure, licensing and environment provisioning.
- Changes not traceable to a requirement listed in section 5.

## 5. Functional Requirements

{chr(10).join(rows)}

## 6. Business Rules

{chr(10).join(business_rules)}

## 7. Process Flow

1. User initiates the {self.ctx.process_name} transaction in Maximo.
2. The configured fields and validations described in section 5 apply.
3. Downstream objects are updated according to the business rules in section 6.
4. Any integration defined for this change publishes on the trigger stated in its requirement.

## 8. Assumptions and Dependencies

- Maximo {self.ctx.cfg.maximo_version} is available in the target environment.
- Names marked "To be confirmed" in section 5 are resolved before the technical design is approved.
- Validation for this document was performed against the {self.ctx.validator.source_label()}.

## 9. Open Questions

{chr(10).join(open_questions)}
"""

    def _confidence_flags(self):
        """Flag any change item the classifier was not confident about."""
        threshold = self.ctx.cfg.confidence_threshold
        from core.models import Flag

        out = []
        for item in self.change_items():
            if item.confidence < threshold:
                out.append(
                    Flag(
                        section="5. Functional Requirements",
                        item=item.title[:80],
                        reason=(
                            f"Change type classified as '{item.change_type.value}' with "
                            f"confidence {item.confidence:.2f}, below the {threshold} threshold."
                        ),
                        confidence=item.confidence,
                        severity="warn",
                        suggestion="Confirm the change type at the review gate.",
                    )
                )
        return out

    # -- emit --------------------------------------------------------------
    def emit(self, composition: Composition) -> list[Artifact]:
        out = self.ctx.artifact_dir("01_fdd")
        artifacts: list[Artifact] = []

        md_path = out / "FDD.md"
        md_path.write_text(composition.body, encoding="utf-8")
        artifacts.append(self.register_artifact(md_path, kind="md", description="FDD source markdown"))

        docx_path = out / "FDD.docx"
        render(
            composition.body,
            template=self.ctx.cfg.template_path("fdd"),
            target=docx_path,
            title=f"{self.ctx.process_name} - Functional Design Document",
            subtitle=self.ctx.state.title,
        )
        artifacts.append(
            self.register_artifact(docx_path, kind="docx", description="Production-ready FDD")
        )

        flag_path = out / "FDD_flag_report.md"
        flag_path.write_text(self._flag_report(composition), encoding="utf-8")
        artifacts.append(
            self.register_artifact(flag_path, kind="md", description="Low-confidence items for review")
        )
        return artifacts

    def _flag_report(self, composition: Composition) -> str:
        flags = composition.flags
        lines = [
            "# FDD Flag Report",
            "",
            f"Run: {self.ctx.state.run_id}",
            f"Validation source: {self.ctx.validator.source_label()}",
            "",
            self.report.summary(),
            "",
        ]
        if not flags:
            lines.append("No items fell below the confidence threshold. Nothing requires review.")
            return "\n".join(lines)

        lines += [
            f"{len(flags)} item(s) require human review before this FDD is approved.",
            "",
            "| # | Section | Item | Confidence | Severity | Reason | Suggestion |",
            "|---|---|---|---|---|---|---|",
        ]
        for n, f in enumerate(sorted(flags, key=lambda x: x.confidence), 1):
            lines.append(
                f"| {n} | {_cell(f.section)} | {_cell(f.item)} | {f.confidence:.2f} | "
                f"{f.severity} | {_cell(f.reason)} | {_cell(f.suggestion) or '-'} |"
            )
        return "\n".join(lines)


def _cell(text: str, width: int = 300) -> str:
    """Make text safe for a markdown table cell."""
    clean = " ".join((text or "").split()).replace("|", "\\|")
    return clean[:width] + ("..." if len(clean) > width else "")


def _status_tokens(text: str, process: dict, group: str) -> list[str]:
    """Statuses from `group` that actually appear in the text."""
    allowed = [s for s in (process.get("statuses", {}) or {}).get(group, [])]
    upper = (text or "").upper()
    return [s for s in allowed if f" {s}" in upper or f"{s} " in upper]
