"""Agent 4 - Testing Agent (blueprint section 4).

Generates the functional test case workbook covering every change described in
the FDD and TDD. Coverage requirements from the blueprint:

  * happy path for every requirement
  * negative / error path for every validation rule
  * integration test cases for every interface from Agent 3B
  * regression: existing Maximo functions each change could disturb
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from core.models import Artifact, ChangeItem, DuplicateDecision, Phase
from rendering.xlsx_writer import TESTCASE_COLUMNS, write_testcases

from .base import BaseAgent, Composition

#: Maximo areas a change to each object typically disturbs.
_REGRESSION_MAP = {
    "WORKORDER": ["Work Order Tracking search", "WO status change", "Planned vs actual costs", "Assignment Manager"],
    "ASSET": ["Asset hierarchy rollup", "Asset status change", "Meter reading entry"],
    "JOBPLAN": ["Job Plan revision", "PM generation", "Work order generation from job plan"],
    "CUJP": ["CU estimate rollup", "CU to work order generation", "CU catalogue search"],
    "LOCATIONS": ["Location hierarchy", "Asset move", "Location status"],
    "ITEM": ["Item master search", "Inventory balance", "Storeroom issue"],
}


class TestingAgent(BaseAgent):
    agent_id = "4"
    name = "Testing Agent"
    phase = Phase.TEST
    doc_type = "testcases"
    role = (
        "Produce a complete functional test case set, detailed enough that a "
        "tester can execute it against a Maximo instance without further guidance."
    )
    inputs_description = "- The approved FDD and TDD\n- Interfaces defined by Agent 3B\n- The change item register"
    output_format = (
        "JSON only: an array of test case objects with the keys "
        '"Test Case ID", "Module", "Scenario", "Type", "Pre-conditions", "Test Steps", '
        '"Expected Result", "Notes". '
        '"Type" is one of: Happy path, Negative, Integration, Regression. '
        '"Test Steps" is a single string with numbered steps separated by newlines.'
    )
    skill_files = ("mx_core_SKILL.md",)

    # -- gather ------------------------------------------------------------
    def gather(self) -> dict[str, Any]:
        items = self.change_items()
        for item in items:
            self.ctx.validator.check_change_item(item, self.ctx.process, self.report)

        interfaces: list[dict[str, Any]] = []
        result = self.ctx.state.result(Phase.BUILD_INTEGRATION)
        if result:
            for artifact in result.artifacts:
                if artifact.name == "mif_components.json":
                    path = Path(artifact.path)
                    if path.exists():
                        try:
                            interfaces = json.loads(path.read_text(encoding="utf-8"))
                        except json.JSONDecodeError:
                            interfaces = []
        return {"items": items, "interfaces": interfaces}

    # -- compose -----------------------------------------------------------
    def compose(self, facts: dict[str, Any], duplicate: DuplicateDecision) -> Composition:
        rows = self._deterministic_cases(facts)
        generated_by = "deterministic"

        if self.ctx.llm.available:
            enriched = self._model_cases(facts)
            if enriched:
                rows = self._merge(rows, enriched)
                generated_by = "model-enriched"

        for n, row in enumerate(rows, 1):
            row["Test Case ID"] = f"TC-{n:03d}"
            row.setdefault("Actual Result", "")
            row.setdefault("Pass/Fail", "")

        self.facts["rows"] = rows
        counts: dict[str, int] = {}
        for row in rows:
            counts[row["Type"]] = counts.get(row["Type"], 0) + 1
        breakdown = ", ".join(f"{v} {k.lower()}" for k, v in sorted(counts.items()))

        body = self._coverage_markdown(rows, facts)
        summary = f"{len(rows)} test case(s): {breakdown}. Generated by {generated_by}."
        return Composition(body=body, summary=summary, flags=[], generated_by=generated_by)

    def _deterministic_cases(self, facts: dict[str, Any]) -> list[dict[str, Any]]:
        module = self.ctx.process_name
        apps = self.ctx.process.get("applications") or ["the application"]
        app = apps[0]
        rows: list[dict[str, Any]] = []

        for item in facts["items"]:
            label = _cell(item.title, 110)
            field = item.maximo_attribute or "the new field"
            obj = item.maximo_object or "the record"

            # Happy path - one per requirement.
            rows.append(
                {
                    "Module": module,
                    "Scenario": f"{label} - happy path",
                    "Type": "Happy path",
                    "Pre-conditions": f"User has write access to {app}. A {obj} record exists.",
                    "Test Steps": (
                        f"1. Log in to Maximo and open {app}.\n"
                        f"2. Open an existing {obj} record.\n"
                        f"3. Locate {field} and enter a valid value.\n"
                        f"4. Save the record."
                    ),
                    "Expected Result": (
                        f"The record saves without error and {field} retains the entered value "
                        f"after the record is reopened."
                    ),
                    "Notes": f"Change item {item.id}",
                }
            )

            # Negative path - one per validation-bearing requirement.
            if item.change_type.value in {"customisation", "config", "workflow"}:
                rows.append(
                    {
                        "Module": module,
                        "Scenario": f"{label} - negative path",
                        "Type": "Negative",
                        "Pre-conditions": f"User has write access to {app}.",
                        "Test Steps": (
                            f"1. Open {app} and select a {obj} record.\n"
                            f"2. Leave {field} empty, or enter a value longer than the configured length.\n"
                            f"3. Attempt to save."
                        ),
                        "Expected Result": (
                            "Maximo rejects the invalid entry with a clear message, or leaves the "
                            "existing value untouched. No partial update is committed."
                        ),
                        "Notes": f"Change item {item.id}",
                    }
                )

            # Regression - based on the object being touched.
            for area in _REGRESSION_MAP.get((item.maximo_object or "").upper(), [])[:2]:
                rows.append(
                    {
                        "Module": module,
                        "Scenario": f"Regression - {area} after {label[:60]}",
                        "Type": "Regression",
                        "Pre-conditions": f"The change for {item.id} is applied in the test environment.",
                        "Test Steps": (
                            f"1. Exercise {area} exactly as before the change.\n"
                            f"2. Compare the result against the pre-change baseline."
                        ),
                        "Expected Result": f"{area} behaves exactly as it did before the change.",
                        "Notes": f"Impacted by change item {item.id}",
                    }
                )

        for iface in facts["interfaces"]:
            name = iface.get("name", "interface")
            rows.append(
                {
                    "Module": f"{module} Integration",
                    "Scenario": f"{name} - message generated on trigger",
                    "Type": "Integration",
                    "Pre-conditions": (
                        f"{iface.get('external_system', 'External system')} is enabled and the "
                        f"{'publish channel' if iface.get('publish_channel') else 'enterprise service'} is active."
                    ),
                    "Test Steps": (
                        f"1. Create or open a {iface.get('object', 'record')} record.\n"
                        f"2. Apply the trigger: {iface.get('trigger', 'the defined event')}.\n"
                        f"3. Open Message Tracking and locate the message."
                    ),
                    "Expected Result": (
                        f"Exactly one message is produced on {name} and every field matches "
                        f"the field mapping in the Integration Build Document."
                    ),
                    "Notes": f"Interface {name}",
                }
            )
            rows.append(
                {
                    "Module": f"{module} Integration",
                    "Scenario": f"{name} - no message outside the trigger condition",
                    "Type": "Negative",
                    "Pre-conditions": f"{name} is active.",
                    "Test Steps": (
                        f"1. Open a {iface.get('object', 'record')} record.\n"
                        f"2. Make a change that does NOT satisfy: {iface.get('trigger', 'the trigger')}.\n"
                        f"3. Check Message Tracking."
                    ),
                    "Expected Result": "No message is generated.",
                    "Notes": f"Interface {name}",
                }
            )
            rows.append(
                {
                    "Module": f"{module} Integration",
                    "Scenario": f"{name} - endpoint unavailable",
                    "Type": "Negative",
                    "Pre-conditions": f"{name} is active; the endpoint is deliberately unreachable.",
                    "Test Steps": (
                        "1. Disable the target endpoint.\n"
                        "2. Apply the trigger condition.\n"
                        "3. Open Message Reprocessing."
                    ),
                    "Expected Result": (
                        "The message is held in the error queue with a clear reason and can be "
                        "reprocessed once the endpoint is restored. No data is lost."
                    ),
                    "Notes": f"Interface {name}",
                }
            )
        return rows

    def _model_cases(self, facts: dict[str, Any]) -> list[dict[str, Any]]:
        items = "\n".join(
            f"- {i.id} [{i.change_type.value}] {i.title}: {i.description[:250]}" for i in facts["items"]
        )
        ifaces = "\n".join(
            f"- {i.get('name')} ({i.get('direction')}) trigger={i.get('trigger')}" for i in facts["interfaces"]
        ) or "(none)"
        user = (
            f"BUSINESS PROCESS: {self.ctx.process_name}\n\n"
            f"CHANGE ITEMS:\n{items}\n\nINTERFACES:\n{ifaces}\n\n"
            f"VALIDATED MAXIMO FACTS:\n{self.validated_facts_block()}\n\n"
            "Produce functional test cases covering: a happy path for every change item, a "
            "negative path for every validation rule, an integration case for every interface, "
            "and regression cases for existing Maximo functions each change could disturb. "
            "Return the JSON array only."
        )
        try:
            parsed, reply = self.ctx.llm.complete_json(self.system_prompt(), user, max_tokens=8000)
        except Exception as exc:
            self.log.warning("model test-case generation failed (%s) - using deterministic set", exc)
            return []
        if not reply.ok or not isinstance(parsed, list):
            return []

        rows: list[dict[str, Any]] = []
        for entry in parsed:
            if not isinstance(entry, dict) or not entry.get("Scenario"):
                continue
            rows.append({k: str(entry.get(k, "")) for k in TESTCASE_COLUMNS if k in entry or k != "Test Case ID"})
        return rows

    def _merge(self, base: list[dict], extra: list[dict]) -> list[dict]:
        """Keep the deterministic backbone, add distinct model-written cases."""
        seen = {_key(r) for r in base}
        merged = list(base)
        for row in extra:
            if _key(row) in seen:
                continue
            row.setdefault("Module", self.ctx.process_name)
            row.setdefault("Type", "Happy path")
            merged.append(row)
            seen.add(_key(row))
        return merged

    def _coverage_markdown(self, rows: list[dict], facts: dict[str, Any]) -> str:
        per_item: dict[str, dict[str, int]] = {}
        for row in rows:
            note = row.get("Notes", "")
            key = note.replace("Change item ", "").replace("Impacted by change item ", "").strip() or "General"
            bucket = per_item.setdefault(key, {"Happy path": 0, "Negative": 0, "Integration": 0, "Regression": 0})
            bucket[row["Type"]] = bucket.get(row["Type"], 0) + 1

        table = ["| Requirement / Change Item | Happy path | Negative | Integration | Regression | Total |", "|---|---|---|---|---|---|"]
        for key, counts in sorted(per_item.items()):
            total = sum(counts.values())
            table.append(
                f"| {key} | {counts['Happy path']} | {counts['Negative']} | "
                f"{counts['Integration']} | {counts['Regression']} | {total} |"
            )

        return f"""# Test Coverage Summary

| Field | Value |
|---|---|
| Business process | {self.ctx.process_name} |
| Run ID | {self.ctx.state.run_id} |
| Change items covered | {len(facts['items'])} |
| Interfaces covered | {len(facts['interfaces'])} |
| Total test cases | {len(rows)} |

## Coverage by change item

{chr(10).join(table)}

## Coverage rules applied

- Happy path for every functional requirement.
- Negative / error path for every validation rule.
- Integration test cases for every interface defined by Agent 3B, including the
  no-message and endpoint-failure paths.
- Regression cases for existing Maximo functions each change could disturb.

The executable workbook is `testcase.xlsx`. Actual Result and Pass/Fail are left
blank for the tester.
"""

    # -- emit --------------------------------------------------------------
    def emit(self, composition: Composition) -> list[Artifact]:
        out = self.ctx.artifact_dir("04_test")
        rows = self.facts.get("rows", [])
        artifacts: list[Artifact] = []

        summary_rows = []
        per_item: dict[str, dict[str, int]] = {}
        for row in rows:
            note = row.get("Notes", "")
            key = note.replace("Change item ", "").replace("Impacted by change item ", "").strip() or "General"
            bucket = per_item.setdefault(key, {"Happy path": 0, "Negative": 0, "Integration": 0, "Regression": 0})
            bucket[row["Type"]] = bucket.get(row["Type"], 0) + 1
        for key, counts in sorted(per_item.items()):
            summary_rows.append(
                [key, counts["Happy path"], counts["Negative"], counts["Integration"], counts["Regression"], sum(counts.values())]
            )

        xlsx = out / "testcase.xlsx"
        write_testcases(rows, xlsx, summary_rows=summary_rows)
        artifacts.append(
            self.register_artifact(xlsx, kind="xlsx", description=f"{len(rows)} functional test cases")
        )

        md = out / "Test_Coverage_Summary.md"
        md.write_text(composition.body, encoding="utf-8")
        artifacts.append(self.register_artifact(md, kind="md", description="Coverage summary"))
        return artifacts


def _key(row: dict) -> str:
    return " ".join(str(row.get("Scenario", "")).lower().split())[:80]


def _cell(text: str, width: int = 240) -> str:
    clean = " ".join((text or "").split()).replace("|", "\\|")
    return clean[:width] + ("..." if len(clean) > width else "")
